import * as THREE from 'three';
import { createMenuInput } from './controller-menu.js';
const menuInput=createMenuInput();
let activeCheckpoint=null;
let running=false;
import { Reflector } from './Reflector.js';
import { RoomEnvironment } from './RoomEnvironment.js';
let environmentMap;
const $=id=>document.getElementById(id);
const sources={facts:'https://www.911memorial.org/learn/resources/digital-exhibitions/world-trade-center-history/world-trade-center-facts-and-figures',life:'https://www.911memorial.org/learn/resources/digital-exhibitions/world-trade-center-history/snapshots-work-life',history:'https://www.911memorial.org/learn/resources/digital-exhibitions/world-trade-center-history',windows:'https://collection.911memorial.org/Detail/objects/6980/rel/1',plate:'https://collection.911memorial.org/Detail/objects/117745/rel/1',lobby:'https://commons.wikimedia.org/wiki/File:World_Trade_Center_lobby,_08-19-2000.png'};
const checkpoints=[
 {id:1,room:'lobby',x:23,z:15,title:'A city within a city',subtitle:'The people behind the skyline',body:'The World Trade Center was a place of ordinary routines on an extraordinary scale. About 50,000 people worked across the seven-building complex, while tens of thousands more passed through each day. Office workers shared the site with delivery staff, cleaners, engineers, visitors, and people meeting for lunch.',question:'What kinds of work make a building of this scale possible, beyond the jobs in its offices?',fact:'These workforce figures describe the entire World Trade Center complex, not just the North Tower.',source:'facts'},
 {id:2,room:'lobby',x:25,z:-21,title:'The grand arrival',subtitle:'Architecture at human scale',body:'Tall windows, polished stone, plants, and changing daylight gave the lobby a very different character from the towers’ distant silhouettes. The photograph below shows the North Tower in August 2000, looking south along its east side. Compare the window rhythm, planting, and reflective floor with this interpretation.',question:'How does your impression of the tower change when you stand inside rather than view it from a distance?',fact:'The photograph is documentary evidence. This model approximates proportions and materials; furniture, circulation, and decorative details have not been surveyed.',source:'lobby',photo:true},
 {id:3,room:'lobby',x:-7,z:-17,title:'A vertical transportation network',subtitle:'Express elevators and sky lobbies',body:'The Twin Towers used both express and local elevators. Passengers could transfer at sky lobbies rather than require every elevator shaft to serve every floor. This made an exceptionally tall building function as a practical workplace. The elevator doors nearby connect the spaces in this educational walk.',question:'Why might a very tall building need a system more like a transit network than a single elevator?',fact:'The model uses direct connections for convenience. It does not reproduce the original elevator dispatch system, exact routes, cabin finishes, or travel times.',source:'facts'},
 {id:4,room:'office',x:22,z:14,title:'An ordinary working day',subtitle:'A representative office',body:'The towers contained a wide range of organizations and workplaces. This illustrative office evokes the period through desktop computers, paper files, shared desks, and meeting rooms. It represents the everyday activities that made the towers lived-in places, rather than a documented tenant’s suite.',question:'Which details of work around 2000 feel familiar, and which have changed?',fact:'This office is a composite. Its arrangement, equipment, and furnishings are not attributed to a specific tenant or floor.',source:'life'},
 {id:5,room:'office',x:27,z:-18,title:'A narrow window onto New York',subtitle:'The view from a workplace',body:'Architect Minoru Yamasaki designed the towers’ typical windows to be only about 20 inches wide. The Memorial Museum explains that this narrow scale was intended to help people who were uneasy at great heights while still allowing floor-to-ceiling views.',question:'Would narrow windows make you feel more secure at this height? How might design affect comfort?',fact:'Typical window width is documented. The city outside is an atmospheric, simplified backdrop, not an accurate map or verified skyline of 2000.',source:'windows'},
 {id:6,room:'restaurant',x:22,z:16,title:'Windows on the World',subtitle:'Hospitality above the city',body:'Windows on the World opened in 1976 on the North Tower’s 106th and 107th floors. After closing following the 1993 bombing, it reopened in 1996 under new management. The restaurant made the building a destination for celebrations, dining, and business gatherings.',question:'What makes a restaurant part of a city’s cultural memory, beyond its food?',fact:'This dining room evokes the period but is not a measured reconstruction of the 1996 interior. Table positions, upholstery, lighting, and finishes are interpretive.',source:'plate'},
 {id:7,room:'restaurant',x:-22,z:17,title:'A world of people',subtitle:'The work behind the welcome',body:'In 2001, the Windows on the World restaurant operation and its subsidiary venues employed around 450 people who spoke more than 60 languages. Hospitality depended on a large community of cooks, servers, stewards, managers, and other workers.',question:'Whose work is visible when you visit a restaurant, and whose work happens out of sight?',fact:'The staffing figures refer to the restaurant operation and its subsidiary venues. The empty scene does not suggest the real spaces were unoccupied.',source:'facts'},
 {id:8,room:'restaurant',x:25,z:-21,title:'More than an icon',subtitle:'A place to meet and remember',body:'The North Tower’s upper floors hosted a collection of dining and event spaces. By 2000, these included Windows on the World, Wild Blue, and the Greatest Bar on Earth. The public observation deck was in the South Tower. Here, the panorama was part of dining, gathering, and everyday work.',question:'After exploring these interiors, how would you describe the World Trade Center to someone who knows it only through the attacks?',fact:'Only an interpretive dining space is modeled here. It does not reproduce every venue or service area of floors 106–107.',source:'life'}
];
const roomInfo={lobby:['LOBBY LEVEL','The grand arrival'],office:['OFFICE LEVEL · ILLUSTRATIVE','An ordinary working day'],restaurant:['FLOORS 106–107 · INTERPRETIVE SPACE','Windows on the World'],elevator:['EXPRESS ELEVATOR','Between worlds']};
let scene,camera,renderer,world,obstacles=[],markers=[],room='lobby',yaw=0,pitch=0,started=false,panelMode=null,nearest=null,rideState=null,visited=new Set(),lastTime=0,prevButtons=[],menuIndex=0,keys={},drag=null,focusedBefore=null,reflection=null;
let settings={speed:2.7,sensitivity:1,invert:false,quality:'high'};
try{const saved=JSON.parse(localStorage.getItem('north-tower-tour-v1')||'{}');visited=new Set((saved.visited||[]).filter(n=>n>=1&&n<=8));Object.assign(settings,saved.settings||{});}catch{}
function save(){try{localStorage.setItem('north-tower-tour-v1',JSON.stringify({visited:[...visited],settings}));}catch{}}
function seeded(seed){let v=seed;return ()=>{v=(v*1664525+1013904223)>>>0;return v/4294967296;};}const rand=seeded(1228);
function texture(kind){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');if(kind==='marble'){ctx.fillStyle='#c3c7c6';ctx.fillRect(0,0,512,512);for(let n=0;n<200;n++){let x=rand()*700-100,y=rand()*512;ctx.beginPath();ctx.moveTo(x,y);for(let j=0;j<8;j++){x+=rand()*110-30;y+=rand()*60-20;ctx.lineTo(x,y);}ctx.strokeStyle=`rgba(55,72,79,${rand()*.1})`;ctx.lineWidth=rand()*3;ctx.stroke();}}else if(kind==='carpet'){ctx.fillStyle='#233b3f';ctx.fillRect(0,0,512,512);for(let i=0;i<26000;i++){ctx.fillStyle=rand()>.5?'#80908b24':'#071b252a';ctx.fillRect(rand()*512,rand()*512,1+rand()*2,1);}}else if(kind==='wood'){ctx.fillStyle='#67472f';ctx.fillRect(0,0,512,512);for(let i=0;i<650;i++){ctx.fillStyle=`rgba(25,14,7,${rand()*.16})`;ctx.fillRect(rand()*512,0,rand()*3,512);}}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(kind==='marble'?3:8,kind==='marble'?3:8);t.anisotropy=8;return t;}
const mats={marble:new THREE.MeshStandardMaterial({map:texture('marble'),roughness:.24,metalness:.12}),pale:new THREE.MeshStandardMaterial({color:0xe3e0d5,roughness:.65}),metal:new THREE.MeshStandardMaterial({color:0xaeb8b9,roughness:.25,metalness:.78}),dark:new THREE.MeshStandardMaterial({color:0x122930,roughness:.62}),wood:new THREE.MeshStandardMaterial({map:texture('wood'),roughness:.43}),carpet:new THREE.MeshStandardMaterial({map:texture('carpet'),roughness:1}),gold:new THREE.MeshStandardMaterial({color:0xaa9769,metalness:.7,roughness:.32}),glass:new THREE.MeshPhysicalMaterial({color:0xd5e1de,roughness:.03,metalness:.05,transparent:true,opacity:.11,depthWrite:false,side:THREE.DoubleSide}),light:new THREE.MeshStandardMaterial({color:0xfff2d6,emissive:0xffdfad,emissiveIntensity:2}),cloth:new THREE.MeshStandardMaterial({color:0xebe7da,roughness:.94}),chair:new THREE.MeshStandardMaterial({color:0x303b65,roughness:.86})};
function box(w,h,d,x,y,z,mat=mats.pale,solid=false){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;world.add(m);if(solid)obstacles.push({x1:x-w/2-.32,x2:x+w/2+.32,z1:z-d/2-.32,z2:z+d/2+.32});return m;}
function cylinder(rt,rb,h,x,y,z,mat=mats.metal,n=20){const m=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,n),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;world.add(m);return m;}
function lineTube(points,r,mat){const curve=new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p)));const m=new THREE.Mesh(new THREE.TubeGeometry(curve,24,r,8,false),mat);world.add(m);m.castShadow=true;return m;}
function label(text,x,y,z,w=3,h=.55,color='#e5e6da',bg='#19323b'){const c=document.createElement('canvas');c.width=1024;c.height=192;const ctx=c.getContext('2d');ctx.fillStyle=bg;ctx.fillRect(0,0,c.width,c.height);ctx.save();ctx.scale(-1,1);ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='500 58px Arial';ctx.fillText(text,-512,100,960);ctx.restore();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide}));m.position.set(x,y,z);world.add(m);return m;}
function plant(x,z,scale=1){cylinder(.7*scale,.58*scale,.95*scale,x,.475*scale,z,mats.metal);cylinder(.63*scale,.63*scale,.03,x,.96*scale,z,mats.dark);cylinder(.045*scale,.075*scale,2.1*scale,x,1.8*scale,z,mats.wood,9);for(let i=0;i<5;i++){const a=i*1.256;lineTube([[x,1.5*scale,z],[x+Math.cos(a)*.3*scale,2.3*scale,z+Math.sin(a)*.3*scale],[x+Math.cos(a)*.8*scale,2.8*scale,z+Math.sin(a)*.8*scale]],.022*scale,mats.wood);}
 const leafMat=new THREE.MeshStandardMaterial({color:0x355f36,roughness:.85,side:THREE.DoubleSide});const leafGeo=new THREE.SphereGeometry(1,6,4);const leaves=new THREE.InstancedMesh(leafGeo,leafMat,550);const matrix=new THREE.Object3D();for(let i=0;i<550;i++){const a=rand()*Math.PI*2,r=Math.sqrt(rand())*1.12*scale;matrix.position.set(x+Math.cos(a)*r,(2.5+rand()*.8)*scale,z+Math.sin(a)*r);matrix.rotation.set(rand()*2,rand()*6,rand()*2);matrix.scale.set(.055*scale,.016*scale,(.08+rand()*.065)*scale);matrix.updateMatrix();leaves.setMatrixAt(i,matrix.matrix);leaves.setColorAt(i,new THREE.Color().setHSL(.25+rand()*.09,.25+rand()*.3,.13+rand()*.15));}leaves.castShadow=true;leaves.receiveShadow=true;world.add(leaves);obstacles.push({x1:x-.85*scale,x2:x+.85*scale,z1:z-.85*scale,z2:z+.85*scale});}
function archPier(x,z,rot){const shape=new THREE.Shape();shape.moveTo(-.36,0);shape.lineTo(-.36,8.4);shape.quadraticCurveTo(-.36,11.8,-2.33,14.4);shape.lineTo(2.33,14.4);shape.quadraticCurveTo(.36,11.8,.36,8.4);shape.lineTo(.36,0);shape.closePath();const m=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.55,bevelEnabled:false,curveSegments:16}),mats.marble);m.position.set(x,0,z);m.rotation.y=rot;m.castShadow=m.receiveShadow=true;world.add(m);}
function roomShell(height,carpet=false){box(63,.22,63,0,-.13,0,carpet?mats.carpet:mats.marble);box(63,.3,63,0,height,0,mats.pale);for(const axis of [0,1]){for(let side of [-1,1]){const glass=box(axis===0?.06:63,height,axis===0?63:.06,axis===0?side*31.4:0,height/2,axis===1?side*31.4:0,mats.glass);glass.castShadow=false;box(axis===0?.25:63,.3,axis===0?63:.25,axis===0?side*31.3:0,.15,axis===1?side*31.3:0,mats.metal);}}
}
function city(high){const ground=new THREE.Mesh(new THREE.PlaneGeometry(2400,2400),new THREE.MeshStandardMaterial({color:high?0x91acb4:0xb3b9b5,roughness:.9}));ground.rotation.x=-Math.PI/2;ground.position.y=high?-160:-.3;world.add(ground);const rng=seeded(560);for(let i=0;i<140;i++){const a=rng()*Math.PI*2,dist=90+rng()*750;const x=Math.cos(a)*dist,z=Math.sin(a)*dist;const h=15+rng()*80;box(10+rng()*28,h,10+rng()*28,x,(high?-160:0)+h/2,z,new THREE.MeshStandardMaterial({color:new THREE.Color().setHSL(.54,.08,.46+rng()*.23),roughness:.85}));}}
function lights(height){scene.add(new THREE.HemisphereLight(0xd6e8f1,0xb9babc,2.6));const sun=new THREE.DirectionalLight(0xffefd7,4);sun.position.set(65,42,-15);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-46,right:46,top:46,bottom:-46,near:1,far:160});sun.shadow.bias=-.0005;sun.shadow.normalBias=.035;scene.add(sun);const fill=new THREE.DirectionalLight(0xb6d9f8,1.2);fill.position.set(-40,20,30);scene.add(fill);for(const x of [-22,22])for(let z=-24;z<=24;z+=8){box(.85,.16,.85,x,height-.3,z,mats.gold);box(.68,.06,.68,x,height-.42,z,mats.light);}}
function core(h=4){box(24,h,32,0,h/2,4,mats.marble,true);for(const x of [-7,0,7]){box(2.8,3.2,.1,x,1.6,-12.08,mats.metal);box(.035,3.2,.08,x,1.6,-12.16,mats.dark);box(3.2,.22,.18,x,3.4,-12.1,mats.dark);label(x===0?'EXPRESS':'LOCAL',x,3.75,-12.18,2.2,.35);box(.2,.4,.14,x+1.65,1.25,-12.1,mats.gold);}
 label('ELEVATORS',0,4.5,-12.18,4,.55);}
function lobby(){roomShell(14.5);city(false);lights(14.5);core(14.3);
 // Slender exterior columns branch toward the ceiling, evoking the lobby facade.
 for(const side of [-1,1])for(let z=-28;z<=28;z+=4.67)archPier(side*30.8,z,Math.PI/2);
 for(const side of [-1,1])for(let x=-28;x<=28;x+=4.67)archPier(x,side*30.8,0);
 for(let z=-25;z<=25;z+=6.25)box(17,.07,.09,22,14.25,z,mats.metal);
 for(const x of [-17,17])box(5,.035,54,x,.01,0,mats.carpet);
 for(const x of [-28,28])for(const z of [-24,-12,0,12,24])plant(x,z,1.15);
 // Polished surface underlay with a restrained planar reflection.
 reflection=new Reflector(new THREE.PlaneGeometry(63,63),{color:0x7b8588,textureWidth:Math.min(innerWidth,1280),textureHeight:Math.min(innerHeight,900),clipBias:.003});reflection.rotation.x=-Math.PI/2;reflection.position.y=.005;world.add(reflection);
 const sheen=box(63,.012,63,0,.015,0,new THREE.MeshStandardMaterial({map:mats.marble.map,transparent:true,opacity:.65,roughness:.3,metalness:.1}));sheen.castShadow=false;
 // A glass-railed lower-concourse stair feature; not a mapped archival stair.
 for(const x of [21,24]){box(2,1.1,6,x,.52,0,mats.dark,true);for(let i=0;i<16;i++)box(1.5,.06,.28,x,.2+i*.056,2.2-i*.28,mats.metal);for(const s of [-1,1]){const rail=box(.07,1.15,6.1,x+s*.92,1.2,0,mats.glass);rail.castShadow=false;box(.09,.09,6.2,x+s*.92,1.8,0,mats.metal);}}
 label('CONCOURSE',22.5,2.2,-3.1,4,.45);label('1 WORLD TRADE CENTER',0,6.5,-12.2,10,.8,'#293a40','#c4c9c5');
 for(const x of [-7,0,7]){box(4.5,.1,3,x,.03,-27,mats.carpet);box(.15,3.2,2.5,x,1.6,-30,mats.metal);box(2.7,3.2,.08,x,1.6,-30,mats.glass);}
}
function upperWindows(height,wide=false){for(const side of [-1,1])for(let n=-30;n<=30;n+=wide?2.4:1.02){box(.5,height,.6,n,height/2,side*31,mats.pale);box(.6,height,.5,side*31,height/2,n,mats.pale);}for(const side of [-1,1]){box(63,.16,.35,0,.65,side*31,mats.metal);box(.35,.16,63,side*31,.65,0,mats.metal);}}
function chair(x,z,angle=0,office=false){const group=new THREE.Group();world.add(group);const create=(w,h,d,y,zz,mat)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(0,y,zz);m.castShadow=true;m.receiveShadow=true;group.add(m);};create(.58,.13,.57,.5,0,office?mats.dark:mats.chair);create(.58,.61,.1,.88,.23,office?mats.dark:mats.chair);for(const sx of [-.22,.22])for(const sz of [-.2,.2]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.022,.022,.5,8),mats.metal);leg.position.set(sx,.25,sz);group.add(leg);}group.position.set(x,0,z);group.rotation.y=angle;obstacles.push({x1:x-.42,x2:x+.42,z1:z-.42,z2:z+.42});}
function desk(x,z){box(2.6,.09,1.3,x,.77,z,mats.wood,true);for(const s of [-1,1])box(.08,.73,1.1,x+s*1.13,.37,z,mats.metal);box(.56,.47,.42,x,.77+.3,z-.15,mats.pale);box(.45,.34,.015,x,1.09,z+.067,new THREE.MeshStandardMaterial({color:0x2b5965,emissive:0x17323b,emissiveIntensity:.5}));box(.65,.05,.23,x,.85,z+.43,mats.pale);for(let i=0;i<4;i++)box(.32,.006,.4,x+.78,.84+i*.012,z+.2,mats.cloth);cylinder(.07,.06,.15,x-.7,.9,z+.25,mats.pale);chair(x,z+1.2,0,true);}
function office(){roomShell(4.1,true);city(true);lights(4.1);core(4);upperWindows(4);for(const x of [-22,22])for(const z of [-7,0,7]){desk(x,z);box(5,1.25,.09,x,.63,z-1.25,mats.pale);}
 for(const x of [-22,22])for(const z of [-25,25])plant(x,z,.8);
 for(let x=-9;x<=9;x+=6){box(3,1.1,.6,x,.55,23,mats.pale,true);for(let n=0;n<3;n++){box(2.8,.025,.05,x,.35+n*.3,23.32,mats.metal);box(.35,.035,.08,x,.49+n*.3,23.35,mats.dark);}}
 box(6,.1,2.6,-22,.78,20,mats.wood,true);for(const z of [18.1,21.9])for(const x of [-24,-22,-20])chair(x,z,z<20?Math.PI:0,true);for(let z=-30;z<30;z+=2.5)box(63,.025,.025,0,4,z,mats.metal);for(let x=-30;x<30;x+=2.5)box(.025,.025,63,x,4,0,mats.metal);label('OFFICE LEVEL',0,3.75,-12.2,4,.4);}
function table(x,z){cylinder(1.12,1.12,.09,x,.8,z,mats.cloth,48);cylinder(.11,.13,.75,x,.39,z,mats.gold);cylinder(.52,.52,.06,x,.06,z,mats.gold);for(let a=0;a<4;a++){const ang=a*Math.PI/2;chair(x+Math.sin(ang)*1.65,z+Math.cos(ang)*1.65,ang);const px=x+Math.sin(ang)*.73,pz=z+Math.cos(ang)*.73;cylinder(.24,.24,.022,px,.87,pz,mats.cloth,32);cylinder(.18,.18,.014,px,.89,pz,mats.pale,32);const gx=px+.25;cylinder(.045,.06,.12,gx,.98,pz,mats.glass,16);cylinder(.012,.012,.12,gx,.91,pz,mats.glass,8);box(.025,.012,.3,px-.28,.88,pz,mats.metal);}
 cylinder(.08,.1,.25,x,.96,z,mats.gold);obstacles.push({x1:x-1.3,x2:x+1.3,z1:z-1.3,z2:z+1.3});}
function restaurant(){roomShell(4.8,true);city(true);lights(4.8);upperWindows(4.65,true);box(24,4.6,26,0,2.3,0,mats.wood,true);for(const x of [-5,0,5]){box(2.6,3.1,.1,x,1.55,-13.1,mats.metal);box(.025,3,.06,x,1.5,-13.17,mats.dark);}label('WINDOWS ON THE WORLD',0,3.7,-13.2,9,.65,'#d9c898','#263846');
 for(const x of [-23,-17,17,23])for(const z of [-8,0,8])table(x,z);
 for(const x of [-8,0,8])table(x,23);
 for(const x of [-28,28])for(const z of [-26,26])plant(x,z,.95);
 box(16,1.05,1.6,0,.53,16,mats.wood,true);box(16.3,.09,1.9,0,1.1,16,mats.marble);for(let x=-6;x<=6;x+=2){cylinder(.32,.32,.09,x,.8,18,mats.chair);cylinder(.035,.05,.76,x,.4,18,mats.gold);}
 for(const x of [-23,-17,17,23])for(const z of [-8,0,8]){cylinder(.01,.01,1.1,x,4.2,z,mats.gold,6);cylinder(.22,.46,.28,x,3.6,z,mats.cloth);cylinder(.39,.39,.02,x,3.45,z,mats.light);}
}
function elevator(){box(4.5,.1,4.5,0,-.06,0,mats.marble);box(4.5,.1,4.5,0,3,0,mats.pale);for(const x of [-2.25,2.25])box(.1,3,4.5,x,1.5,0,mats.wood);box(4.5,3,.1,0,1.5,2.25,mats.wood);box(4.5,3,.1,0,1.5,-2.25,mats.metal);box(.025,3,.08,0,1.5,-2.18,mats.dark);for(const x of [-2.17,2.17])box(.08,.08,3.8,x,1,0,mats.gold);box(2,.05,2,0,2.9,0,mats.light);scene.add(new THREE.HemisphereLight(0xffe5bc,0x40525a,3));label('1 WORLD TRADE CENTER',0,2.5,-2.17,2.5,.3);}
function marker(cp){const g=new THREE.Group();g.position.set(cp.x,0,cp.z);const ring=new THREE.Mesh(new THREE.RingGeometry(.47,.52,48),new THREE.MeshBasicMaterial({color:0xdccc99,side:THREE.DoubleSide,transparent:true,opacity:.85}));ring.rotation.x=-Math.PI/2;ring.position.y=.055;g.add(ring);const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#17343be8';ctx.beginPath();ctx.arc(64,64,54,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#e1cf9c';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#e7d7b0';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='50px Georgia';ctx.fillText(String(cp.id).padStart(2,'0'),64,66);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),depthTest:true}));sprite.position.y=1.8;sprite.scale.set(.85,.85,1);g.add(sprite);world.add(g);markers.push({cp,g,sprite});}
function setRoom(next,spawn){running=false;if(world){scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.isReflector)o.dispose();});}scene=new THREE.Scene();scene.background=new THREE.Color(next==='elevator'?0x263c43:0xb1c7d3);scene.environment=environmentMap;scene.environmentIntensity=.65;scene.fog=new THREE.FogExp2(0xb1c7d3,next==='lobby'?.0017:.0022);world=new THREE.Group();scene.add(world);room=next;obstacles=[];markers=[];reflection=null;({lobby,office,restaurant,elevator}[next])();if(next!=='elevator')checkpoints.filter(c=>c.room===next).forEach(marker);camera.position.set(...(spawn|| (next==='elevator'?[0,1.68,1]:[22,1.68,24])));yaw=next==='elevator'?0:-.12;pitch=0;const [tag,title]=roomInfo[next];$('floorTag').textContent=tag;$('roomName').textContent=title;$('mapWrap').hidden=!started||next==='elevator';$('roomNote').textContent=next==='lobby'?'Approximate architecture · historical reference available':'Illustrative layout and furnishings · circa 2000';applyQuality();}
function applyQuality(){if(!renderer)return;renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='high'?1.7:1));renderer.shadowMap.enabled=settings.quality==='high';if(reflection)reflection.visible=settings.quality==='high';renderer.setSize(innerWidth,innerHeight);save();}
function boot(){try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;const pmrem=new THREE.PMREMGenerator(renderer);const studio=new RoomEnvironment();environmentMap=pmrem.fromScene(studio,.04).texture;studio.dispose();pmrem.dispose();camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.08,1800);camera.rotation.order='YXZ';setRoom('lobby');requestAnimationFrame(frame);}catch(e){$('error').hidden=false;$('error').textContent='The 3D world could not start. Open this page in a browser with WebGL 2 and hardware acceleration enabled. '+e.message;}}
function start(){started=true;$('welcome').hidden=true;['location','bottom','mapWrap','crosshair'].forEach(id=>$(id).hidden=false);$('touch').hidden=!matchMedia('(pointer:coarse)').matches;updateProgress();}
function unlock(){if(document.pointerLockElement)document.exitPointerLock();keys={};drag=null;}
function openPanel(mode,eyebrow,html){unlock();focusedBefore=document.activeElement;panelMode=mode;$('panel').hidden=$('veil').hidden=false;$('panelEyebrow').textContent=eyebrow;$('panelBody').innerHTML=html;$('panel').scrollTop=0;$('interact').hidden=true;menuIndex=0;menuInput.reset();const first=(mode==='guide'||mode==='destinations')?($('panelBody').querySelector('button:not(:disabled),input,select')||$('close')):$('close');first.focus({preventScroll:true});highlightControl(first);}
function closePanel(){menuInput.reset();document.querySelectorAll('.controller-focus').forEach(el=>el.classList.remove('controller-focus'));panelMode=null;$('panel').hidden=$('veil').hidden=true;focusedBefore?.focus?.();}
function showCheckpoint(cp){activeCheckpoint=cp;visited.add(cp.id);save();updateProgress();openPanel('checkpoint','CHECKPOINT '+String(cp.id).padStart(2,'0')+' / 08',`<h2 id="panelTitle">${cp.title}</h2><h3>${cp.subtitle}</h3><p>${cp.body}</p>${cp.photo?`<figure><img src="lobby-2000.png" alt="North Tower lobby in August 2000, with tall windows, reflective stone, potted trees, and escalators"><figcaption>North Tower, August 19, 2000. Smurfy / Wikimedia Commons, <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener">CC BY-SA 3.0</a>. Source image retouched: chain removed, lights desaturated, brightness adjusted.</figcaption></figure>`:''}<div class="fact">${cp.fact}</div><a class="source" href="${sources[cp.source]}" target="_blank" rel="noopener">Historical source ↗ ${cp.source==='lobby'?'Photograph and attribution':'9/11 Memorial & Museum'}</a><h3>Pause & discuss</h3><p>${cp.question}</p><div class="actions"><button id="continueWalk">Continue walking <span>○</span></button><button id="nextPoint">Next checkpoint <span>R1</span></button></div>`);$('continueWalk').onclick=closePanel;$('nextPoint').onclick=()=>visitCheckpoint(checkpoints[cp.id%8]);}
function updateProgress(){$('progress').textContent=`${visited.size} / 8 checkpoints visited`;}
function visitCheckpoint(cp){if(!started)start();closePanel();if(room!==cp.room)setRoom(cp.room);camera.position.set(cp.x,1.68,cp.z+2);yaw=0;pitch=0;nearest={type:'checkpoint',cp};}
function guide(){openPanel('guide','EXPLORE AT YOUR OWN PACE',`<h2 id="panelTitle">The everyday tower</h2><p>Walk to the numbered markers, or choose a checkpoint to move there. Read all eight to complete the visit.</p><div class="check-list">${checkpoints.map(c=>`<button data-cp="${c.id}"><span class="number">${visited.has(c.id)?'✓':String(c.id).padStart(2,'0')}</span><span>${c.title}<small>${roomInfo[c.room][1]}</small></span></button>`).join('')}</div><p class="muted">These shortcuts are navigation aids, not original building routes.</p><button id="guideElevator">Choose a destination</button>`);document.querySelectorAll('[data-cp]').forEach(b=>b.onclick=()=>visitCheckpoint(checkpoints[Number(b.dataset.cp)-1]));$('guideElevator').onclick=elevatorMenu;}
function settingsPanel(){openPanel('settings','VISITOR GUIDE',`<h2 id="panelTitle">Make yourself at home.</h2><p>Connect your PS5 controller in your device’s Bluetooth settings, then press × while this page is active. A standard browser controller mapping is required.</p><div class="controls"><div>Left stick / L3<br><span>Move / toggle running (2× speed)</span></div><div>Right stick<br><span>Look around</span></div><div>× / Circle<br><span>Interact / close</span></div><div>△ / Options<br><span>Checkpoints / pause</span></div><div>Left stick or D-pad / ×<br><span>Choose menu item / select</span></div><div>L1 / R1<br><span>Previous / next checkpoint</span></div></div><p class="muted">In panels: right stick scrolls the text. Left stick or D-pad moves the highlighted selection; left/right adjusts sliders. × selects, ○ closes, and △ opens the checkpoint list. L1 / R1 opens the previous / next historical checkpoint.</p><p class="muted">Keyboard: WASD or arrows to walk, drag to look, E to interact, G for checkpoints, Esc to pause. Click the world to capture the mouse; Esc releases it. Touch: use the arrows and drag the view.</p><label class="setting">Walking speed <input id="speed" type="range" min="1" max="5" step=".1" value="${settings.speed}" aria-label="Walking speed"></label><label class="setting">Look sensitivity <input id="sensitivity" type="range" min=".3" max="2" step=".1" value="${settings.sensitivity}" aria-label="Look sensitivity"></label><label class="setting">Invert vertical look <input id="invert" type="checkbox" ${settings.invert?'checked':''}></label><label class="setting">Graphics <select id="quality"><option value="high" ${settings.quality==='high'?'selected':''}>Detailed</option><option value="low" ${settings.quality==='low'?'selected':''}>Performance</option></select></label><button id="openGuide">View checkpoints</button><div class="fact">About this reconstruction<br>Created for historical learning. The lobby uses a dated photograph as a visual reference. Other spaces are illustrative composites. Dimensions, decorations, sightlines, elevator travel, and the distant city are approximate. This is not a full 110-floor model or a photorealistic, archival replica.</div><a class="source" href="${sources.history}" target="_blank" rel="noopener">Explore the Memorial Museum’s WTC history ↗</a><button id="resume">${started?'Resume walking':'Enter the tower'} <span>○</span></button>`);for(const k of ['speed','sensitivity'])$(k).oninput=e=>{settings[k]=Number(e.target.value);save();};$('invert').onchange=e=>{settings.invert=e.target.checked;save();};$('quality').onchange=e=>{settings.quality=e.target.value;applyQuality();};$('openGuide').onclick=guide;$('resume').onclick=()=>{if(!started)start();closePanel();};}
function elevatorMenu(){openPanel('destinations','ELEVATOR CONNECTIONS',`<h2 id="panelTitle">Where to?</h2><p>Travel between the three walkable spaces.</p>${[['lobby','Lobby','Grand arrival and the life of the complex'],['office','Office level','A representative workplace around 2000'],['restaurant','Windows on the World','An interpretation of the upper-floor dining spaces']].map(([r,t,d])=>`<button class="destination" data-room="${r}" ${r===room?'disabled':''}>${t}${r===room?' · You are here':''}<small>${d}</small></button>`).join('')}<p class="muted">Direct connections and a short journey are used for this tour. Actual routes involved different banks of elevators, and sometimes transfers.</p>`);document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>takeElevator(b.dataset.room));}
function takeElevator(target){if(!started)start();const from=room;closePanel();rideState={target,elapsed:0,from:from==='restaurant'?107:from==='office'?64:1,to:target==='restaurant'?107:target==='office'?64:1};setRoom('elevator');$('ride').hidden=false;$('rideTo').textContent=roomInfo[target][1]+(target==='office'?' · illustrative level':'');}
function arrive(){if(!rideState)return;const target=rideState.target;rideState=null;$('ride').hidden=true;setRoom(target,[0,1.68,target==='restaurant'?-17:-16]);yaw=Math.PI;}
function interact(){if(!started){start();return;}if(rideState){arrive();return;}if(nearest?.type==='elevator')elevatorMenu();else if(nearest?.cp)showCheckpoint(nearest.cp);}
function nearUpdate(){if(room==='elevator')return;let best=null,bestD=3.5;for(const cp of checkpoints.filter(c=>c.room===room)){const d=Math.hypot(camera.position.x-cp.x,camera.position.z-cp.z);if(d<bestD){bestD=d;best={type:'checkpoint',cp};}}
 const ez=room==='restaurant'?-13:-12;const ed=Math.hypot(camera.position.x,camera.position.z-ez);if(ed<3.1)best={type:'elevator'};nearest=best;$('interact').hidden=!started||!!panelMode||!best;if(best)$('interactText').textContent=best.type==='elevator'?'Use the elevators':best.cp.title;}
function canMove(x,z){if(room==='elevator')return Math.abs(x)<1.8&&Math.abs(z)<1.8;if(Math.abs(x)>30||Math.abs(z)>30)return false;return !obstacles.some(b=>x>b.x1&&x<b.x2&&z>b.z1&&z<b.z2);}
function move(dx,dz,dt,multiplier=1){const len=Math.hypot(dx,dz);if(len>1){dx/=len;dz/=len;}const speed=settings.speed*multiplier*dt;const vx=(dx*Math.cos(yaw)+dz*Math.sin(yaw))*speed,vz=(-dx*Math.sin(yaw)+dz*Math.cos(yaw))*speed;const steps=Math.max(1,Math.ceil(Math.hypot(vx,vz)/.15));for(let i=0;i<steps;i++){if(canMove(camera.position.x+vx/steps,camera.position.z))camera.position.x+=vx/steps;if(canMove(camera.position.x,camera.position.z+vz/steps))camera.position.z+=vz/steps;}}
function highlightControl(el){document.querySelectorAll('.controller-focus').forEach(node=>node.classList.remove('controller-focus'));el?.classList.add('controller-focus');}
function menuControls(buttons,axes,now,dt){
 const panel=$('panel');
 const eligible=[...panel.querySelectorAll('button:not(:disabled),a,input,select')].filter(el=>el.getClientRects().length);
 if(!eligible.length)return;
 const input=menuInput.sample(buttons,axes,now);
 let el=document.activeElement;
 if(!eligible.includes(el)){el=eligible.find(node=>node.id!=='close')||eligible[0];el.focus();highlightControl(el);}
 if(input.vertical){const current=eligible.indexOf(el);el=eligible[(current+input.vertical+eligible.length)%eligible.length];el.focus({preventScroll:true});highlightControl(el);el.scrollIntoView({block:'nearest'});}
 if(input.horizontal){
   if(el.type==='range'){el.value=Number(el.value)+input.horizontal*Number(el.step||1);el.dispatchEvent(new Event('input'));}
   else if(el.tagName==='SELECT'){el.selectedIndex=(el.selectedIndex+input.horizontal+el.options.length)%el.options.length;el.dispatchEvent(new Event('change'));}
   else {const current=eligible.indexOf(el);el=eligible[(current+input.horizontal+eligible.length)%eligible.length];el.focus({preventScroll:true});highlightControl(el);el.scrollIntoView({block:'nearest'});}
 }
 if(input.scroll)panel.scrollTop+=input.scroll*550*dt;
 if(buttons[0]&&!prevButtons[0]){
   highlightControl(el);
   if(el.type==='checkbox'){el.checked=!el.checked;el.dispatchEvent(new Event('change'));}
   else if(el.tagName==='SELECT'){el.selectedIndex=(el.selectedIndex+1)%el.options.length;el.dispatchEvent(new Event('change'));}
   else if(el.tagName==='BUTTON'||el.tagName==='A')el.click();
 }
}
function updateRunMode(buttons,standard){if(!standard){running=false;return;}if(started&&!panelMode&&!rideState&&buttons[10]&&!prevButtons[10])running=!running;}
function frame(now){const dt=Math.min((now-lastTime)/1000||.016,.05);lastTime=now;let pad;try{pad=[...(navigator.getGamepads?.()||[])].filter(p=>p?.connected).sort((a,b)=>(/dualsense|054c|playstation|sony/i.test(b.id)?1:0)-(/dualsense|054c|playstation|sony/i.test(a.id)?1:0))[0];}catch{}const buttons=pad?pad.buttons.map(b=>b.pressed):[];const standard=pad?.mapping==='standard';updateRunMode(buttons,standard);$('padStatus').textContent=pad?(standard?(running?'Running · L3 to walk':'Walking · L3 to run'):'Controller detected · standard mapping unavailable'):'Controller: press × to connect';
 if(standard){if(buttons[9]&&!prevButtons[9]){if(panelMode)closePanel();else settingsPanel();}else if(buttons[1]&&!prevButtons[1]&&panelMode)closePanel();else if(panelMode){if(buttons[3]&&!prevButtons[3])guide();else if(panelMode==='checkpoint'&&((buttons[5]&&!prevButtons[5])||(buttons[4]&&!prevButtons[4]))){const cp=checkpoints[(activeCheckpoint.id-1+(buttons[5]?1:-1)+8)%8];visitCheckpoint(cp);showCheckpoint(cp);}else menuControls(buttons,pad.axes,now,dt);}else{if(buttons[0]&&!prevButtons[0])interact();if(buttons[3]&&!prevButtons[3])guide();if(!rideState)for(const n of [4,5])if(buttons[n]&&!prevButtons[n]){const idx=nearest?.cp?nearest.cp.id-1:checkpoints.findIndex(c=>c.room===room);visitCheckpoint(checkpoints[(idx+(n===5?1:-1)+8)%8]);}}
 }prevButtons=buttons;
 if(started&&!panelMode){const dead=v=>Math.abs(v||0)<.16?0:Math.sign(v)*(Math.abs(v)-.16)/.84;const ax=standard?dead(pad.axes[0]):0,az=standard?dead(pad.axes[1]):0;const dx=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+ax,dz=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+az;move(dx,dz,dt,running&&room!=='elevator'?2:1);if(standard){yaw-=dead(pad.axes[2])*dt*1.9*settings.sensitivity;pitch-=dead(pad.axes[3])*dt*1.5*settings.sensitivity*(settings.invert?-1:1);}}
 pitch=THREE.MathUtils.clamp(pitch,-1.2,1.2);camera.rotation.set(pitch,yaw,0,'YXZ');for(const m of markers){m.sprite.position.y=1.8+Math.sin(now*.0015+m.cp.id)*.035;const distance=Math.hypot(camera.position.x-m.cp.x,camera.position.z-m.cp.z);m.sprite.material.opacity=THREE.MathUtils.clamp((distance-.65)/1.1,0,1);}
 if(rideState&&!panelMode){rideState.elapsed+=dt;const t=Math.min(rideState.elapsed/6,1);$('rideNumber').textContent=String(Math.round(THREE.MathUtils.lerp(rideState.from,rideState.to,t))).padStart(2,'0');if(t>=1)arrive();}
 nearUpdate();drawMap();renderer.render(scene,camera);requestAnimationFrame(frame);}
function drawMap(){if($('mapWrap').hidden)return;const ctx=$('map').getContext('2d');ctx.clearRect(0,0,220,180);const s=2.25,cx=110,cy=90;ctx.strokeStyle='#668089';ctx.lineWidth=1;ctx.strokeRect(cx-31*s,cy-31*s,62*s,62*s);ctx.fillStyle='#37515c';ctx.fillRect(cx-12*s,cy+(room==='restaurant'?-13:-12)*s,24*s,(room==='restaurant'?26:32)*s);ctx.font='9px Arial';ctx.textAlign='center';ctx.fillStyle='#a9bfc5';ctx.fillText('CORE',cx,cy+5);for(const cp of checkpoints.filter(c=>c.room===room)){ctx.fillStyle=visited.has(cp.id)?'#83b0a6':'#d9c698';ctx.beginPath();ctx.arc(cx+cp.x*s,cy+cp.z*s,5,0,Math.PI*2);ctx.fill();}ctx.save();ctx.translate(cx+camera.position.x*s,cy+camera.position.z*s);ctx.rotate(-yaw);ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(0,-6);ctx.lineTo(-4,4);ctx.lineTo(4,4);ctx.closePath();ctx.fill();ctx.restore();}
$('enter').onclick=start;$('menuBtn').onclick=settingsPanel;$('guideBtn').onclick=guide;$('close').onclick=closePanel;$('veil').onclick=closePanel;$('interact').onclick=interact;$('skipRide').onclick=arrive;$('mapToggle').onclick=()=>{$('map').hidden=!$('map').hidden;$('mapToggle').textContent=$('map').hidden?'+':'−';};
addEventListener('keydown',e=>{if(panelMode){if(e.code==='Escape'){closePanel();e.preventDefault();}if(e.code==='Tab'){const els=[...$('panel').querySelectorAll('button:not(:disabled),a,input,select')];const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}return;}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='KeyE')interact();if(e.code==='KeyG')guide();if(e.code==='Escape')settingsPanel();});addEventListener('keyup',e=>delete keys[e.code]);addEventListener('blur',()=>{keys={};drag=null;});
$('world').addEventListener('pointerdown',e=>{if(!started||panelMode)return;drag={x:e.clientX,y:e.clientY};$('world').setPointerCapture(e.pointerId);if(e.pointerType==='mouse'&&!document.pointerLockElement){try{const p=$('world').requestPointerLock();p?.catch?.(()=>{});}catch{}}});
addEventListener('pointermove',e=>{if(!started||panelMode)return;let dx=0,dy=0;if(document.pointerLockElement){dx=e.movementX;dy=e.movementY;}else if(drag){dx=e.clientX-drag.x;dy=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};}yaw-=dx*.002*settings.sensitivity;pitch-=dy*.002*settings.sensitivity*(settings.invert?-1:1);});addEventListener('pointerup',()=>drag=null);addEventListener('pointercancel',()=>{drag=null;keys={};});
for(const b of document.querySelectorAll('[data-move]')){const code={forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD'}[b.dataset.move];b.onpointerdown=e=>{e.preventDefault();keys[code]=true;b.setPointerCapture(e.pointerId);};b.onpointerup=b.onpointercancel=()=>delete keys[code];}
addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
// A read-only diagnostic snapshot supports automated verification without changing the world.
window.tourDiagnostics=()=>({room,started,panelMode,visited:[...visited],position:camera?.position.toArray(),checkpoints:checkpoints.length,colliders:obstacles.length,drawCalls:renderer?.info.render.calls,triangles:renderer?.info.render.triangles,webgl:!!renderer});
boot();
